# Generated by Django 4.0.5 on 2022-07-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'фильмы'},
        ),
    ]
