# Generated by Django 4.0.5 on 2022-07-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='lovername',
            field=models.CharField(default='', max_length=250),
        ),
    ]
