# Generated by Django 4.0.5 on 2022-07-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_lovername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='lovername',
            new_name='lowername',
        ),
    ]
