# Generated by Django 4.0.5 on 2022-07-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_lovername_movie_lowername'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
